name: lyydaisy's blog
description: Welcome to my homepage.
meta_description: ""

markdown: redcarpet
pygments: true
highlighter: pygments
logo: false
paginate: 20
paginate_path: "/jekyll/page:num"
baseurl: /jekyll/
domain_name: 'http://lyydaisy.github.io'
excerpt_separator:  '<!-- more -->'

# Details for the RSS feed generator
url:            'http://lyydaisy.github.io/jekyll/'
staitcurl:    'http://lyydaisy.github.io'
author:         'lyydaisy'

